---

# Ansible
# ansible_user: root
ansible_python_interpreter: /usr/bin/python3

# Ubuntu
ubuntu_dist: "Ubuntu"
ubuntu_release: "jammy"
ubuntu_dist_major: "22"
ubuntu_dist_version: "22.04"

# Docker
docker_version: "5:20.10.22"

#Docker-compose
docker_compose_version: "2.14.1"

# Containerd
containerd_version: "1.6.14-1"


# Kubernetes
kube_version: "1.27"
cni_version: "1.2.0-2.1"
master_ip: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4'].address | default(groups['master'][0]) }}"
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf

# Helm
helm_version: "3.7/stable"

# Go
go_version: "1.18.1"
golangci_lint_version: "v1.46.0"

# Node and NPM
node_version: "12.19.0"
npm_version: "6.14.8"
eslint_version: "5.16.0"