---

- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - acl
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: '0644'

- name: Convert Docker GPG key to keyring format
  command: gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg /tmp/docker.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
  become: yes

- name: Add Docker APT repository with signed key
  copy:
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'
  become: yes

- name: Remove temporary Docker GPG key
  file:
    path: /tmp/docker.gpg
    state: absent
  become: yes

- name: Install docker engine
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce={{ docker_version }}~3-0~ubuntu-{{ ubuntu_release }}
    - docker-ce-cli={{ docker_version }}~3-0~ubuntu-{{ ubuntu_release }}
    - containerd.io={{ containerd_version }}
    - docker-compose-plugin={{docker_compose_version}}~ubuntu-{{ ubuntu_release }}

- name: Hold docker version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Verify docker group is present
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: '{{ ansible_user }}'
    append: yes
    groups: docker

- name: Allow {{ ansible_user }} to access containerd socket
  acl:
    path: /run/containerd/containerd.sock
    etype: user
    entity: '{{ ansible_user }}'
    permissions: rw

- name: Set dockerd config
  copy:
    src: "daemon.json"
    dest: /etc/docker/
    owner: root
    group: root
    mode: 0644

- name: dockerd service
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Enable and check Docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_docker
