---

- name: Download Go binaries
  get_url:
    url: "https://dl.google.com/go/go{{go_version}}.linux-amd64.tar.gz"
    dest: "/tmp/go{{go_version}}.linux-amd64.tar.gz"

- name: Install Go
  unarchive:
    remote_src: yes
    src: "/tmp/go{{go_version}}.linux-amd64.tar.gz"
    dest: /usr/local

- name: Create Go working directory
  become: false
  file:
    path: "/home/{{ ansible_user }}/gocode/bin/"
    state: directory

- name: Update profile gopath
  become: false
  lineinfile:
    dest: /home/{{ ansible_user }}/.profile
    state: present
    line: 'export GOPATH=$HOME/gocode'

- name: Update profile path
  become: false
  lineinfile:
    dest: /home/{{ ansible_user }}/.profile
    state: present
    line: 'export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin'

- name: Copy golangci-lint install file
  copy:
    src: "install.sh"
    dest: "/home/{{ ansible_user }}/install-golangci-lint.sh"
    mode: 0744
  tags: golangci-lint

- name: Install golangci-lint
  become: false
  shell: /bin/bash -c "cd /home/{{ ansible_user }}; source /home/{{ ansible_user }}/.profile; bash install-golangci-lint.sh {{golangci_lint_version}}"

# source .bashrc doesn't work so added golang part in .profile. But .profile
# only works if logging into the machine remotely or use login shell option is
# selected in terminal preferences. So adding it in .profile and .bashrc both.

- name: Update bashrc gopath
  become: false
  lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    state: present
    line: 'export GOPATH=$HOME/gocode'

- name: Update bashrc path
  become: false
  lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    state: present
    line: 'export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin'

- name: Apply profile updates
  shell: . ~/.bashrc
  args:
    executable: /bin/bash
  register: bashrc_reload
  changed_when: false
