---
- name: Assert OS is Ubuntu 22.04
  assert:
    that:
      - ansible_distribution == "{{ ubuntu_dist }}"
      - ansible_distribution_major_version == "{{ ubuntu_dist_major }}"
      - ansible_distribution_version == "{{ ubuntu_dist_version }}"
    quiet: yes

- name: Check if golang is installed
  command: /bin/bash -c "source /home/{{ ansible_user }}/.profile; go version | awk '{print $3}' | cut -c 3-"
  register: go_check
  failed_when: "'command not found' in go_check.stdout"

- debug:
    msg: "[WARNING] Current golang version is lower than recommended version {{ go_version }}.\n
    To get the script to install properly, uninstall the existing golang and rerun script.\n
    Also remove all its dependencies and config/data."
  when: go_check.stdout != '' and go_check.stdout is version_compare(go_version, '<')

- name: Install golang if go command not found
  include_tasks:
    file: install.yml
  when: go_check.stdout == ''
