---
- name: Assert OS is Ubuntu 22.04
  assert:
    that:
      - ansible_distribution == "{{ ubuntu_dist }}"
      - ansible_distribution_major_version == "{{ ubuntu_dist_major }}"
      - ansible_distribution_version == "{{ ubuntu_dist_version }}"
    quiet: yes

- name: Remove Helm
  include_tasks:
    file: uninstall.yml

- name: Install Helm
  include_tasks:
    file: install.yml
